name: "Docker Publish"
description: "Build and publish a docker container"
inputs:
  image:
    description: "Name of the image"
    required: true
  tag:
    description: "Tag for the image"
    required: false
    default: ${{ github.ref_name }}
  registry:
    description: "URL of the registry to publish the package to. Defaults to DockerHub."
    required: false
    default: 'docker.io'
  username:
    description: "Username of the registry account"
    required: true
  password:
    description: "Password of the registry account"
    required: true
runs:
  using: composite
  steps:
    - uses: docker/setup-buildx-action@v2

    - uses: docker/login-action@v2
      with:
        registry: ${{inputs.registry}}
        username: ${{inputs.username}}
        password: ${{inputs.password}}

    - uses: docker/metadata-action@v4
      id: meta
      with:
        tags: ${{inputs.tag}}
        images: ${{inputs.registry}}/${{inputs.image}}

    - uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}